# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: nginx_demo
  path.config: "/usr/share/logstash/pipeline/nginx.demo.conf"

- pipeline.id: sql_demo
  path.config: "/usr/share/logstash/pipeline/sql.demo.conf"